import type { Metadata } from 'next'
import './globals.css'
import SideBar from '@/components/sidebar/sidebar'
import Login from '@/components/login/Login'
import { getServerSession } from "next-auth"
import { options } from './api/auth/[...nextauth]/option'

export const metadata: Metadata = {
  title: 'Instagram Clone',
  description: 'Generated by create next app',
  icons: {
    icon: '/instagram_icon.png'
  }
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const auth = false
  const session = await getServerSession(options);

  console.log('session', session)

  return (
    <html>
      <body>
        {children}
        {/* {session?.user ? (
          <>
            <div className='wrapper'>     
              <SideBar />
              <div className='remain_space'>{children}</div>
            </div>
            <div id="portal"></div>
          </>
        ) : <Login />} */}
      </body>
    </html>
  )
}