import type { Metadata } from 'next'
import './globals.css'
import { ToastContainer, toast } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css';

export const metadata: Metadata = {
  title: 'Instagram Clone',
  description: 'Generated by create next app',
  icons: {
    icon: '/instagram_icon.png'
  }
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <body>
        <ToastContainer position='top-right' theme="dark" />
          {children}
          {/* {session?.user ? (
            <>
              <div className='wrapper'>     
                <SideBar />
                <div className='remain_space'>{children}</div>
              </div>
              <div id="portal"></div>
            </>
          ) : <Login />} */}
      </body>
    </html>
  )
}